name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read
  packages: read

jobs:
  main:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./
      - run: |
          dockerfile-tools
